feat: Added support for Django 4.2
openedx/edx-django-release-util pull request #60
Opened 2023-07-17 12:04 UTC by zubairshakoorarbisoft

- Added support for Django 4.2
- Coded used https://github.com/adamchainz/django-upgrade

2023-07-17 18:52 UTC, awais786 commented on release_util/tests/test_check_reserved_keywords/test_app/test_app/settings.py
> -USE_L10N = True
Revert it

2023-07-17 18:53 UTC, awais786 commented on release_util/tests/migrations/test_migrations/0004_fourth.py
> +from django.db import migrations, models
These migrations are not of this ticket. Make them against master branch in separate PR.

2023-07-17 18:54 UTC, awais786 commented on release_util/tests/test_migration_commands.py
> +        for fail_on_unapplied, exit_code in (
revert this also.

2023-07-24 11:58 UTC, awais786 commented on release_util/tests/migrations/test_migrations/0004_fourth.py
> +class Migration(migrations.Migration):
It was added due to https://docs.djangoproject.com/en/4.0/releases/4.0/#migrations-autodetector-changes

2023-07-25 08:20 UTC, UsamaSadiq requested changes
Please bump the package version and add CHANGELOG entry as well.

2023-07-25 08:43 UTC, UsamaSadiq approved these changes

2023-07-25 08:43 UTC, merged

2023-08-09 12:41 UTC, awais786 commented on release_util/tests/migrations/test_migrations/0004_fourth.py
> +class Migration(migrations.Migration):
Als this is test migration nothing to do with prod.